#!/usr/bin/env bash


echo $$ >> /var/run/myscript.pid

handle_sigterm() {
	echo "I hate the kill command"
	cleanup
	exit 0
}

handle_sigint() {
	echo "Y u no love me?!"
}

handle_sigquit() {
	cleanup
	exit 0
}

cleanup() {
	rm -f /var/run/myscript.pid
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

i=0
while [ $i -lt 10 ]
do
	echo "to infinity and beyond"
	sleep 2
done
