#!/usr/bin/env bash
# This script is displaying the content of current directory
# Only the part of the name after the first dash is displayed

for file in *; do
    if [[ "$file" == *-* ]]; then
        echo "$file" | cut -d'-' -f2-
    fi
done
